apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoserver1
  labels:
    app: demoserver1
spec:
  selector:
    matchLabels:
      app: demoserver1
  template:
    metadata:
      labels:
        app: demoserver1
    spec:
      containers:
      - name: demoserver1
        image: gcr.io/windmill-test-containers/tiltdemo/demoserver1
        command: ["/go/bin/demoserver1"]
        ports:
        - containerPort: 8000