FROM golang:1.10

WORKDIR /go/src/github.com/windmilleng/tiltdemo/cmd/demoserver1

ADD ./cmd/demoserver1 .

RUN go install github.com/windmilleng/tiltdemo/cmd/demoserver1

ENTRYPOINT /go/bin/demoserver1